name       : pyqt-builder
version    : 1.10.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt-builder/PyQt-builder-1.10.3.tar.gz : 6ade47445b7d8c08eb96e91ebda5f8b3494b3e7a9da2be343b9d0704419cb5c7
homepage   : https://www.riverbankcomputing.com/software/pyqt-builder/
license    : GPL-3.0-or-later
component  : programming.python
summary    : The PEP 517 compliant PyQt build system
description: |
    PyQt-builder is the PEP 517 compliant build system for PyQt and projects that extend PyQt. It extends the SIP build system and uses Qt's qmake, in conjunction with make, to perform the actual compilation and installation of extension modules.
build      : |
    %python3_setup
install    : |
    %python3_install
