name       : pyqt-builder
version    : 1.13.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt-builder/PyQt-builder-1.13.0.tar.gz : 4877580c38ceb5320e129b381d083b0a8601c68166d8b99707f08fa0a1689eef
homepage   : https://www.riverbankcomputing.com/software/pyqt-builder/
license    : GPL-3.0-or-later
component  : programming.python
summary    : The PEP 517 compliant PyQt build system
description: |
    PyQt-builder is the PEP 517 compliant build system for PyQt and projects that extend PyQt. It extends the SIP build system and uses Qt's qmake, in conjunction with make, to perform the actual compilation and installation of extension modules.
build      : |
    %python3_setup
install    : |
    %python3_install
